version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: p2p-db
    restart: always
    environment:
      POSTGRES_USER: p2p_user
      POSTGRES_PASSWORD: p2p_password
      POSTGRES_DB: p2p_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  node1:
    build: .
    container_name: p2p-node1
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: p2p_user
      DB_PASSWORD: p2p_password
      DB_NAME: p2p_db
    ports:
      - "8081:8080"
    command: ["/app/p2p-node", "8080"]

  node2:
    build: .
    container_name: p2p-node2
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: p2p_user
      DB_PASSWORD: p2p_password
      DB_NAME: p2p_db
    ports:
      - "8082:8080"
    command: ["/app/p2p-node", "8080"]

volumes:
  db_data:
